### ISSUE TITLE
How can add bollywood song ?

### ISSUE THREAD

**Issue by dipenpatel235** [lpinca/binb#23]
How can add bollywood song ?

can u please explain  ?

**Comment by lpinca** [comment]
1. Get the song data from [iTunes Search API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/).
2. Add the data to redis:
  1. Add the [song](https://github.com/lpinca/binb/blob/86e0fb4cb3460e2c5370707f6d4e9b844ad5387d/util/load_sample_tracks.js#L61-L68).
  2. Add the song to the [room](https://github.com/lpinca/binb/blob/86e0fb4cb3460e2c5370707f6d4e9b844ad5387d/util/load_sample_tracks.js#L72).
