### ISSUE TITLE
Not working the minify

### ISSUE THREAD

**Issue by salientroot** [lpinca/binb#24]
Hello,

I was trying to install the binb app on my local.
But I got the error when run the 'npm run minify'.
So hope you to notice how to fix the issue.
Looking forward to haring from you.

Regards,
Salient

**Comment by lpinca** [comment]
What's the error?

**Comment by salientroot** [comment]
Thanks for your respond quickly.
Please look at the below image.
![screenshot from 2016-10-12 09 57 12](https://cloud.githubusercontent.com/assets/10685904/19300321/53d93522-9062-11e6-909e-4e41573f1502.png)

**Comment by lpinca** [comment]
Hmm weird what shell are you using?
It looks like [shell expansion](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html) does not work.

**Comment by salientroot** [comment]
I am just using the Ubuntu shell.
Also I don't understand the shell expansion, so could you explain how I should do?

**Comment by lpinca** [comment]
Can you try to write this command in your shell?
```shell
$ echo public/js/{app,home,leaderboards}
```

The output should be like this:
```shell
public/js/app public/js/home public/js/leaderboard
```

**Comment by salientroot** [comment]
I will try

**Comment by salientroot** [comment]
I got the same results

**Comment by lpinca** [comment]
So brace expansion works, I'm not sure why the npm script fails. Try to run this:
```shell
for f in public/js/{app,home,leaderboards}; do ./node_modules/.bin/uglifyjs $f.js -o $f.min.js; done
```

**Comment by salientroot** [comment]
great, it is running the command.

**Comment by salientroot** [comment]
ok, good. The app is working properly.
Thank you very much.
Also there is CSS issue in the leaderboard when don't have the table data.
Could you explain about it?

**Comment by lpinca** [comment]
Yeah, that's expected when there are no users. I didn't handle the case with 0 users.
Try to add some users and the leaderboard should work as expected.

**Comment by lpinca** [comment]
Closing, please post back if needed.

**Comment by salientroot** [comment]
Hello,

Thanks for your much helping.
I tried to run the app on local port 80, but it is not working now.
Hope to help about the issue.

Thanks

**Comment by lpinca** [comment]
You can't bind the server to port 80 as a regular user.
If you want to do that you have to use `sudo` or use the `root` user.
Anyway it is not recommended.

**Comment by salientroot** [comment]
I see, thanks

**Comment by divya84** [comment]
I had the same issue with the brace expansion for the minify, had to change the code to do them individually.
