### ISSUE TITLE
Typerror with primus

### ISSUE THREAD

**Issue by divya84** [lpinca/binb#25]
I am trying to run this on Ubuntu 14.04 running node v0.10.25 -- I am getting quite a few errors: 

a) with the lambda functions <(a,b,c)  => { }> not being recognized ( I got past them by replacing '=>' with 'function')

b)
> TypeError:Object function Object() { [native code] } has no method 'assign'

which I got past with `Object.assign = require('object-assign')` at the beginning of the corresponding files. 

c) I also got 

> SyntaxError:Use of const in strict mode

 which I got past with `node --harmony app.js`

d) My latest error is 

> /data/binb/node_modules/primus/transformers/faye/server.js:54
      const spark = new this.Spark(
                    ^
TypeError: undefined is not a function

I'm not sure how to get past this. Any hints would be useful. Thanks!

**Comment by lpinca** [comment]
Hi, use a newer version of Node.js, version 0.10 is no longer supported. See https://github.com/nodesource/distributions

**Comment by divya84** [comment]
I had a feeling it might have to do with versions :-) Thats fixed now! Thanks.
