### ISSUE TITLE
Reset Database / Edit Users?

### ISSUE THREAD

**Issue by Scratchmang** [lpinca/binb#34]
Any ideas as to how to re-set the database and or delete / edit users? Is there an "Admin" page for this?

**Comment by lpinca** [comment]
No there isn't, I have a CLI app to handle administrative tasks.

**Comment by Scratchmang** [comment]
OK. Ummm..... So how would I remove / edit a user?

**Comment by lpinca** [comment]
If you want to reset the whole database just use [`FLUSHDB`](https://redis.io/commands/flushdb). Removing a user is more complex as you have to remove all user related data including sessions.

If you don't care about sessions you can remove a user by running the following commands:

```
SREM emails <user_email>
DEL email:<username>
ZREM users <username>
DEL user:<username>
```

**Comment by Scratchmang** [comment]
I'm getting this error....

Command 'srem' not found, did you mean:

  command 'rem' from snap rem (0.12.1)
  command 'srm' from deb secure-delete
  command 'sem' from deb parallel
  command 'rem' from deb remind
  command 'smem' from deb smem

So I'm thinking there's some Database utils that are missing from redis?

**Comment by lpinca** [comment]
Those are Redis commands, you can run them using redis-cli.

**Comment by Scratchmang** [comment]
And today I got a little smarter. Thank you! I think I have got this one sorted now.

**Comment by lpinca** [comment]
Closing then.
