### ISSUE TITLE
An idea to implement

### ISSUE THREAD

**Issue by Igor-Lira** [lpinca/binb#36]
I don't know how to send you a message, so I'll try here.
I have an idea to make the game more competitive and maybe it's not difficult to code.
That would be a weekly rank. So the players could have more thing to achieve. it would be really interesting! There is a brazilian game called Gartic (https://gartic.com.br/) that implements a daily rank and people love that. If you see it, they have also some achivements: if a player has 50k in a room, they get a icon in their profile! Like, if I have 50k in rock: 🤘, or 50 k in pop: 🎤.  This would make people play in others rooms.
If you have a mean -6s and more than 50k: ⌚ and so on.

**Comment by Igor-Lira** [comment]
When you see it, i'll close it :)

**Comment by lpinca** [comment]
Thanks for the suggestions but I'm no longer in active development. No new features will be added.
