### ISSUE TITLE
Some songs are not played

### ISSUE THREAD

**Issue by WhiteTeaDragon** [lpinca/binb#39]
Hello, today I played, an two times the songs just weren't played. This was an issue for at least two separate players. This hasn't happened before. The images for the album covers also didn't load. The pictures capturing that are attached.

![image](https://user-images.githubusercontent.com/60018562/170837419-035f8b86-7a9a-4b36-bde7-b0d1fa968824.png)
![image](https://user-images.githubusercontent.com/60018562/170837421-43762e22-a7f6-4aa6-be6e-1f1163706062.png)

**Comment by lpinca** [comment]
Hello, this is not caused by a code issue. Please use the in-game "feedback & support" feature for issues like this. Anyway, thank you for reporting.

**Comment by lpinca** [comment]
FWIW, this is the situation (at least for my country):

- Guru Josh Project / Infinity
    - The [preview URL](http://a828.phobos.apple.com/us/r1000/107/Music/v4/30/5b/a6/305ba612-fb4f-e796-e9ab-78b0291bcbb8/mzaf_1085721203708648131.aac.m4a) works
    - The [artwork URL](http://a5.mzstatic.com/us/r30/Features/63/b5/08/dj.ndhxzvgi.60x60-50.jpg) no longer works
- Westlife / Uptown Girl
    - The [preview URL](http://a842.phobos.apple.com/us/r30/Music/9a/b4/5a/mzm.axhmgaaq.aac.p.m4a) works
    - The [artwork URL](http://is5.mzstatic.com/image/thumb/Music/v4/14/b7/77/14b777f2-16ff-211a-532a-46b4b67d6c02/source/60x60bb.jpg) works
